const details=[
            ['Nampla'
                ,'2',
                'Delicious food!, Classic South Indian Kerala style food located near Rocher! Their Dum Biryani is a must try.',
                'www.google.com',
                'CBD',
                'images/nampla.png'],
            ['Nampla',
                '3',
                'A thai Restaurant located at CBD. Their dishes are flavour packed, generous and worth the money! TomYumYum is a must have.',
                'www.google.com',
                'CBD',
                'images/nampla.png'],
            ['Nampla',
                '1',
                'A smol cozy coffee house located near Lavender, perfect for slow rainy days. I tried their mocha which hits just perfect.',
                'www.google.com',
                'CBD',
                'images/nampla.png'],
            ['Nampla',
                '2',
                'A smol cozy coffee house located near Lavender, perfect for slow rainy days. I tried their mocha which hits just perfect.',
                'www.google.com',
                'CBD',
                'images/nampla.png'],
            ['Nampla',
                '2',
                'A smol cozy coffee house located near Lavender, perfect for slow rainy days. I tried their mocha which hits just perfect.',
                'www.google.com',
                'CBD',
                'images/nampla.png'],
            ['Nampla',
                '1',
                'A smol cozy coffee house located near Lavender, perfect for slow rainy days. I tried their mocha which hits just perfect.',
                'www.google.com',
                'CBD',
                'images/nampla.png'],
            ['Nampla',
                '2',
                'A smol cozy coffee house located near Lavender, perfect for slow rainy days. I tried their mocha which hits just perfect.',
                'www.google.com',
                'CBD',
                'images/nampla.png'],
            ['Nampla',
                '1',
                'A smol cozy coffee house located near Lavender, perfect for slow rainy days. I tried their mocha which hits just perfect.',
                'www.google.com',
                'CBD',
                'images/nampla.png']
            ];