const details=[
            ['Nampla. @ Marina One'
                ,'2',
                'A revelation of restrained opulence—each dish at Nampla whispers of culinary pedigree and precision. The Thai seabass? A delicate waltz of umami and citrus, so refined it silenced my usually discerning palate. Even the mango sticky rice, often an afterthought elsewhere, arrives as a textural triumph. I rarely return, but this—this deserves a second visit. Perhaps even a third.',
                '1',
                '5 The Straits View, B2-44 The Heart, Marina One, 018935',
                'images/Nampla.jpg'],
            ['Moustache BBQ 大胡子串烧',
                '3',
                'One doesn’t expect culinary poetry in Geylang’s gritty corners—but Moustache BBQ surprises. Each skewer is a masterstroke: the lamb, unapologetically bold; the chicken skin, sinfully crisp. Smoke, spice, and deft technique converge with unfussy confidence. I approached with skepticism; I left plotting my return. Rare is the street-style grill that flirts with finesse—rarer still that it earns my approval. This one? Unquestionably, it does.',
                '2',
                '26 Temple St, Singapore 058571',
                'images/MoustacheBBQ.jpg'],
            ['Xiao Ya Tou',
                '3',
                'A luscious affair of bold tradition and modern indulgence. The lobster kueh pie tee—a flirtation of crunch and opulence—danced across my palate with irreverent grace. The charred sotong, perfectly coy in its smokiness, whispered of midnight secrets. And the hokkien noodles? Positively wicked—brimming with umami and attitude. I wouldn’t deign a second bite…unless it was this divine. A rare triumph of taste and theatre.',
                '3',
                '6 Duxton Hill, #01-01, Singapore 089592',
                'images/XiaoYaTou.jpg'],
            ['RAPPU | Sushi Handrolls, Izakaya & Sakes',
                '3',
                'An indulgent procession of hand rolls, each more refined than the last. The toro—silken and impeccably fresh—melted like butter in a chef’s final flourish: measured, intentional, sublime. The uni arrived like a quiet indulgence, barely contained by its crisp nori. Even the wasabi felt thoughtfully curated. I sipped sake that spoke in well-balanced notes. One doesn’t simply eat here—one participates. And mediocrity, I assure you, is never invited to this table.',
                '3',
                '52 Duxton Rd, Singapore 089516',
                'images/Rappu.jpg'],
            ['GO! KBBQ 고케이 비비큐 ',
                '2',
                "It’s Korean BBQ with a PhD in indulgence. Each cut arrived like a VIP guest: marbled, immaculate, handled with reverence. The beef? A slow-burning seduction over flame, kissed by smoke and finesse. Banchan were no afterthought—each a miniature masterpiece (even the kimchi had gravitas). Frankly, if you're not dining here, are you even doing Korean BBQ properly?",
                '2',
                '76 Amoy St, Singapore 069895',
                'images/Gokbbq.jpg'],
            ['Yakitori Yaoya HANARE',
                '3',
                "Each skewer arrived like a curated artefact—char-grilled with such restraint, such reverence, one might assume the chef trained under a Kyoto master. The tsukune? Silken, smoky poetry. Even the humble chicken wing felt reimagined. This isn’t street food; it’s yakitori elevated to near-sacred ceremony. One does not merely eat here—one submits, gratefully, to the quiet precision of culinary discipline. Excellence, whispering over the highest grade binchotan.",
                '3',
                '66 Circular Rd, #01-01, 049426',
                'images/YakitoriYaoyaHanare.jpg'],
            ['Au Croissant ',
                '2',
                "Flaky perfection with the audacity to rival Parisian patisseries. The croissant—airy, golden-lacquered, unapologetically buttery—shattered with grace at first bite. A whisper of sophistication lingered in each layer, as though kissed by a maître pâtissier. Even the simplest almond variant was couture in pastry form. I came for curiosity, stayed for decadence—and left wondering how such elegance ended up in a humble mall corridor. Très chic, unexpectedly.",
                '1',
                '5 Stadium Walk, #01-54 Leisure Park, Singapore 397693',
                'images/AuCroissant.jpg'],
            ['Plum Village Hakka Restaurant ',
                '3',
                'A rare gem—unassuming in appearance, yet the flavours whisper of ancestral kitchens and generational mastery. The abacus seeds, delicate yet toothsome, danced with understated elegance. Pork belly? Braised with the patience of an old soul. Each bite told a story I didn’t know I needed. Tradition here isn’t rustic—it’s refined. And frankly, if authenticity had a dining room, this would be it.',
                '2',
                '16 Jln Leban, Singapore 577554',
                'images/PlumVillageHakka.jpg'],
            ['Synthesis 食拿酒稳: Traditional Chinese Medical Hall Inspired Restaurant & Cocktail Bar (Suntec City)',
                '3',
                'In this culinary apothecary, the Herbal Poached Rice is no mere dish—it is a silken elixir, fragrant with delicate florals, whispering centuries of wisdom into every grain. Their TCM-inspired cocktails are alchemy in crystal: balanced, beguiling, each sip a quiet revolution for the senses. One leaves not simply satiated, but blessed—palate pampered, convinced that true luxury often arrives quietly, in a teacup.',
                '3',
                '3 Temasek Blvd, Tower 4 #01-643, Singapore 038983',
                'images/Synthesis.jpg'],
            ['BBQ Box (Bugis)',
                '3',
                'In a world cluttered with culinary mediocrity, one arrives at BBQ Box with a quiet skepticism. But then, the lamb skewers. A singular, astonishing moment of pure, unadulterated flavour that speaks of a profound and honest craft. The grilled corn, so often a mere afterthought, becomes a revelation—a burst of smoky sweetness in each kernel that leaves one utterly captivated. A truly remarkable find.',
                '2',
                '21 Tan Quee Lan St, #01-03, Singapore 188108',
                'images/BBQBox.jpg'],
            ['Box n Sticks @ Kandahar ',
                '2',
                'Whispers of umami and fire—Box n Sticks’ skewers flirt with perfection. The mentaiko chicken? Silken, indulgent. Each bite-crafted stick, a gilded affair in balance and char. Even I—famously hard to impress—found my palate intrigued, then thoroughly won over. The space hums with quiet sophistication; service, effortlessly attentive. Not everything earns my praise. But here? I stayed for seconds. Voluntarily.',
                '2',
                '28 Kandahar St, Singapore 198889',
                'images/BoxNSticks.jpg'],
            ['山漫漫翘脚牛肉火锅 Hot Pot Valley',
                '2',
                'One sip of the broth—rich, velvety, an umami sonnet—and I knew mediocrity had no place here. The beef? Hand-selected, marbled like fine art, melting with aristocratic grace. Each dip, each swirl, a curated experience worthy of whispered praise in elite circles. Even the vegetables dared to be exquisite. For once, I didn’t mind finishing the bowl. And darling, that says everything.',
                '3',
                'Raffles Blvd, 6号#02-102/102A 邮政编码: 039594',
                'images/HotPotValley.jpg'],
            ['SHAO 燒 @ Rangoon | Modern Teochew Dining 现代潮菜',
                '3',
                'Here modern Teochew dining reveals itself with theatrical finesse. The marinated crab arrives like a jewelled secret, its sweet brine wrapped in subtle sophistication. The crispy rice seafood broth crackles to life, a symphony of texture and depth that lingers far beyond the final spoonful. Service glides with quiet precision—attentive yet discreet—ensuring each moment unfolds less like dinner, more like a curated performance for the discerning palate.',
                '3',
                '223 Rangoon Rd, #01-01/02, Singapore 218460',
                'images/Shao.jpg'],
            ['Folks Collective',
                '2',
                'At Folks Collective, nestled within the chic enclave of 22 Cross St, dining transcends mere sustenance—it becomes a statement. Their green curry is unapologetically rich and lemak, luxuriating in creamy coconut indulgence that would disappoint even the most exacting palate. For those who refuse second helpings unless taste is beyond reproach, the value here is quietly remarkable—the comfort of authentic Thai complexity at commendably modest prices.',
                '1',
                '22 Cross St, #01-50/51/52/53 Exchange, Singapore 048421',
                'images/FolksCollective.jpg'],
            ['Cheeselads',
                '2',
                'Cheese platters here are assembled with the elegance of a jeweller’s case, each selection gleaming with pedigree. I return, unfailingly, for rare finds—individual wheels and wedges that sing with provenance. Their truffle brie is a decadent whisper of earth and cream, an indulgence I accept without hesitation. Why entertain mediocrity when one can savour excellence? For my palate, only Cheeselads suffices; every purchase here is less transaction, more triumph.',
                '2',
                '28 Kandahar St, Singapore 198889',
                'images/Cheeselads.jpg']              
            ];
